### ISSUE TITLE
New paper on one-shot GAN image generation

### ISSUE THREAD

**Issue by ygrayson** [bcmi/Awesome-Few-Shot-Image-Generation#2]
https://openaccess.thecvf.com/content/CVPR2021W/LLID/papers/Sushko_One-Shot_GAN_Learning_To_Generate_Samples_From_Single_Images_and_CVPRW_2021_paper.pdf

Perhaps this should also be included?

Thanks

**Comment by ustcnewly** [comment]
Thanks for your suggestion. We have included this paper.
